# Generated by Django 5.0.1 on 2026-02-28 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('team_lead', 'Team Lead'), ('program_coordinator', 'Program Coordinator'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_open', models.BooleanField(default=True)),
                ('results_released', models.BooleanField(default=False)),
                ('voting_closed_at', models.DateTimeField(blank=True, null=True)),
                ('results_released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'System State',
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('allowed', models.BooleanField(default=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('device_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('eligible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('positions', models.ManyToManyField(related_name='candidates', to='api.position')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField()),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='api.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='api.position')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('position', 'winner')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='api.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.position')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.voter')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('voter', 'position')},
            },
        ),
    ]
